# SPDX-License-Identifier: Unlicense OR 0BSD

# - https://docs.github.com/pt/actions
# - https://github.com/marketplace/actions/flutter-action

name: flutter-quick-test

# Replace 'programma-exemplum-flutter' with your app name

on:
  push:
    # branches:
    #   - main
    # Sequence of patterns matched against refs/tags
    # tags:
    #   - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10
jobs:
  flutter-quick-test:
    name: flutter-quick-test
    runs-on: ubuntu-latest
    continue-on-error: false
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: '12.x'
      - uses: subosito/flutter-action@v1
        with:
          # flutter-version: '1.20.2'
          # channel: 'beta'
          channel: 'stable' # or: 'beta', 'dev' or 'master'
      - run: dart --version
      - run: flutter --version
      - run: flutter pub get
      - run: flutter test
