# SPDX-License-Identifier: Unlicense OR 0BSD

# - https://docs.github.com/pt/actions
# - https://github.com/marketplace/actions/flutter-action

name: flutter-quick-test

on:
  push:
    # _[por-Latn] Execute este fluxo de trabalho em qualquer evento push [por-Latn]_

jobs:

  # _[por-Latn] Teste rápido: se é para falhar, falhe rápido! [por-Latn]_
  flutter-quick-test:
    name: flutter-quick-test
    runs-on: ubuntu-latest
    continue-on-error: false
    steps:

      #### actions/checkout ____________________________________________________
      # _[por-Latn] Clone o repositório para esta máquine de testes [por-Latn]_
      - uses: actions/checkout@v2

      #### actions/setup-java __________________________________________________
      # _[por-Latn] Prepare dependências Java [por-Latn]_
      - uses: actions/setup-java@v1
        with:
          java-version: '12.x'

      #### subosito/flutter-action _____________________________________________
      # @see https://github.com/marketplace/actions/flutter-action

      - uses: subosito/flutter-action@v1
        with:
          # flutter-version: '1.20.2'
          channel: 'stable' # or: 'beta', 'dev' or 'master'
      - run: dart --version
      - run: flutter --version
      - run: flutter pub get

      # _[por-Latn] Execute testes do Flutter [por-Latn]_
      - run: flutter test
