# SPDX-License-Identifier: Unlicense OR 0BSD

# - https://docs.github.com/pt/actions
# - https://github.com/marketplace/actions/flutter-action

name: flutter-build

# Replace 'programma-exemplum-flutter' with your app name

on:
  push:
    branches:
      - main
    # Sequence of patterns matched against refs/tags
    # tags:
    #   - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10

jobs:
  # flutter-quick-test #########################################################
  # _[por-Latn] Teste rápido: se é para falhar, falhe rápido! [por-Latn]_
  flutter-quick-test:
    name: flutter-quick-test
    runs-on: ubuntu-latest
    continue-on-error: false
    steps:
      #### actions/checkout ____________________________________________________
      # _[por-Latn] Clone o repositório para esta máquina de testes [por-Latn]_
      - uses: actions/checkout@v2

      #### actions/setup-java __________________________________________________
      # _[por-Latn] Prepare dependências Java [por-Latn]_
      - uses: actions/setup-java@v1
        with:
          java-version: "12.x"

      #### subosito/flutter-action _____________________________________________
      # @see https://github.com/marketplace/actions/flutter-action

      - uses: subosito/flutter-action@v1
        with:
          # flutter-version: '1.20.2'
          channel: "stable" # or: 'beta', 'dev' or 'master'
      - run: dart --version
      - run: flutter --version
      - run: flutter pub get

      # _[por-Latn] Execute testes do Flutter [por-Latn]_
      - run: flutter test

  flutter-build-unixes:
    name: flutter-build-${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        # os: [ubuntu-latest, windows-latest, macos-latest]
        os: [ubuntu-latest, macos-latest]
    needs: [flutter-quick-test]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: "12.x"
      - uses: subosito/flutter-action@v1
        with:
          # flutter-version: '1.20.2'
          # channel: 'beta'
          channel: "stable" # or: 'beta', 'dev' or 'master'
      - run: dart --version
      - run: flutter --version
      - run: flutter pub get
      - run: flutter test

      - run: flutter build web
        if: startsWith(matrix.os,'ubuntu')

      - run: 'echo "TODO: discover where web folder is, then upload it as zip"'

      - run: flutter build apk
        if: startsWith(matrix.os,'ubuntu')

      - uses: actions/upload-artifact@v2
        if: startsWith(matrix.os,'ubuntu')
        with:
          name: programma-exemplum-flutter.apk
          path: build/app/outputs/flutter-apk/app-release.apk

      - run: flutter build appbundle
        if: startsWith(matrix.os,'ubuntu')

      - uses: actions/upload-artifact@v2
        if: startsWith(matrix.os,'ubuntu')
        with:
          name: programma-exemplum-flutter.aab
          path: build/app/outputs/bundle/release/app-release.aab

      - run: flutter build ios --release --no-codesign
        if: startsWith(matrix.os,'macos')

      - uses: actions/upload-artifact@v2
        if: startsWith(matrix.os,'macos')
        with:
          name: programma-exemplum-flutter.app
          path: build/ios/iphoneos/Runner.app
          retention-days: 5 # 5 days retention (this is an huge folder)

  flutter-build-windows:
    name: Test on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        # os: [ubuntu-latest, windows-latest, macos-latest]
        os: [windows-latest]
    needs: [flutter-quick-test]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: "12.x"
      - uses: subosito/flutter-action@v1
        with:
          # 2021-10-25: channel: beta required for windows
          channel: beta
      - run: dart --version
      - run: flutter --version
      - run: flutter pub get
      - run: flutter test

      # gambiarra to not re-create the project on beta channel just to test windows
      - run: flutter create --platforms=windows --template app --project-name programma_exemplum_flutter --org ai.etica.hxl .
        continue-on-error: true

      - run: flutter config --enable-windows-desktop
        continue-on-error: true

      - run: flutter build windows
        continue-on-error: true

  # TODO:
  # - avancado https://github.com/anton-yurchenko/git-release
  #   - "Unreleased" https://github.com/anton-yurchenko/git-release/issues/47
  # - sem changelog: https://github.com/svenstaro/upload-release-action
